
import { createClient } from '@supabase/supabase-js';

export const config = {
  runtime: 'nodejs',
};

const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY;
const PIKA_API_KEY = process.env.PIKA_API_KEY; // This should be your FAL_KEY

const supabase = createClient(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_ANON_KEY || 'placeholder'
);

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { prompt, aspectRatio, userId } = req.body;

  if (!prompt || !userId) {
    return res.status(400).json({ error: 'Missing required parameters: prompt or userId' });
  }

  if (!PIKA_API_KEY) {
    return res.status(500).json({ error: 'PIKA_API_KEY (Fal.ai Key) is not configured on the server.' });
  }

  try {
    // 1. Initiate Generation with Fal.ai (Async Queue)
    // Using the fal-ai pika model endpoint via queue for reliable async handling
    const initiateResponse = await fetch('https://queue.fal.run/fal-ai/pika/v2/turbo/text-to-video', {
      method: 'POST',
      headers: {
        'Authorization': `Key ${PIKA_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: prompt,
        aspect_ratio: aspectRatio === '16:9' ? '16:9' : '9:16',
      }),
    });

    if (!initiateResponse.ok) {
      const errorData = await initiateResponse.json();
      throw new Error(errorData.detail || errorData.message || 'Fal.ai synthesis failed to start.');
    }

    const { request_id } = await initiateResponse.json();

    if (!request_id) {
      throw new Error('Failed to retrieve request_id from Fal.ai.');
    }

    // 2. Poll for Status (Exclusive Fal.ai Polling)
    let videoUrl = '';
    let attempts = 0;
    const maxAttempts = 25; // 25 attempts * 2s = 50s total (stays within Vercel Pro 60s limit)
    const pollInterval = 2000; // 2 seconds between polls for faster resolution

    while (attempts < maxAttempts) {
      attempts++;
      
      // Wait before polling
      await new Promise(resolve => setTimeout(resolve, pollInterval));

      const statusResponse = await fetch(`https://queue.fal.run/fal-ai/pika/v2/turbo/text-to-video/requests/${request_id}`, {
        headers: { 
          'Authorization': `Key ${PIKA_API_KEY}`,
          'Content-Type': 'application/json'
        }
      });

      if (statusResponse.ok) {
        const statusData = await statusResponse.json();
        
        // Fal.ai status check
        if (statusData.status === 'COMPLETED') {
          videoUrl = statusData.video?.url;
          break;
        } else if (statusData.status === 'FAILED') {
          throw new Error('Fal.ai synthesis process reported a failure.');
        }
        // If status is 'IN_PROGRESS' or 'IN_QUEUE', we continue polling
      } else {
        console.warn(`Polling attempt ${attempts} failed with status: ${statusResponse.status}`);
      }
    }

    // Fallback if the process is taking too long for the serverless function
    if (!videoUrl) {
      throw new Error('Synthesis timed out. The video is still being generated by the neural core.');
    }

    // 3. Save to Supabase 'generations' table (Logic Unchanged)
    if (SUPABASE_URL && SUPABASE_ANON_KEY) {
        const { error: supabaseError } = await supabase
          .from('generations')
          .insert([
            {
              user_id: userId,
              type: "video",
              prompt: prompt,
              result_url: videoUrl,
              created_at: new Date().toISOString()
            }
          ]);
        
        if (supabaseError) {
            console.error('Supabase persistence error:', supabaseError);
        }
    }

    return res.status(200).json({ videoUrl });

  } catch (error: any) {
    console.error('Pika/Fal Production Error:', error);
    return res.status(500).json({ error: error.message || 'An internal error occurred during synthesis.' });
  }
}
