
import { GoogleGenAI } from "@google/genai";

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { prompt, aspectRatio = '1:1' } = req.body;

  try {
    if (!process.env.API_KEY) {
      throw new Error('API_KEY is not configured on the server.');
    }

    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    // Fix: Use correct contents structure as per nano banana model guidelines (gemini-2.5-flash-image)
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: { parts: [{ text: prompt }] },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any
        }
      }
    });

    // Find the image part, do not assume it is the first part.
    const part = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
    
    if (!part?.inlineData?.data) {
      throw new Error('No image generated by the AI model.');
    }

    return res.status(200).json({ 
      imageUrl: `data:${part.inlineData.mimeType};base64,${part.inlineData.data}` 
    });
  } catch (error: any) {
    console.error('API Image Error:', error);
    return res.status(500).json({ error: error.message || 'Image synthesis failed.' });
  }
}
