
import { GoogleGenAI } from "@google/genai";

export default async function handler(req: any, res: any) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  const { prompt, aspectRatio = '1:1' } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: 'Prompt is required' });
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: [{ parts: [{ text: prompt }] }],
      config: {
        imageConfig: {
          aspectRatio
        }
      }
    });

    // Extracting the first image part from candidates
    const part = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
    
    if (!part?.inlineData?.data) {
      throw new Error('No image generated by the AI model.');
    }

    const base64Data = part.inlineData.data;
    const imageUrl = `data:${part.inlineData.mimeType};base64,${base64Data}`;

    return res.status(200).json({ imageUrl });
  } catch (error: any) {
    console.error('API Image Error:', error);
    return res.status(500).json({ error: error.message || 'Image synthesis failed.' });
  }
}
